name: Build distributable version
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and push
        steps:
        -   name: Checkout git repository
            uses: actions/checkout@v3

        -   name: Install dependencies
            run: npm install

        -   name: Build
            run: npm run build

        -   name: Commit
            run: |
                git config --local user.email "fred@xpple.dev"
                git config --local user.name "xpple"
                git commit -a -m "Update build branch"

        -   name: Remove files that shouldn't get pushed
            run: rm -rf .github .idea .vscode node_modules .gitignore package.json tsconfig.json

        -   name: Publish
            uses: ad-m/github-push-action@master
            with:
                force: true
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: dist
