name: Build distributable version
on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and push
        steps:
        -   name: Checkout git repository
            uses: actions/checkout@v2

        -   name: Install dependencies
            run: npm install

        -   name: Build
            run: npm run build

        -   name: Remove files that shouldn't get pushed
            run: rm -rf .git .gitignore node_modules package.json package-lock.json tsconfig.json .idea .github .vscode

        -   name: Publish directory
            uses: s0/git-publish-subdir-action@v2.5.1
            env:
                REPO: "self"
                BRANCH: "dist"
                FOLDER: "."
                GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                MESSAGE: "Update build branch"
